// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CLOthings.Models;

public partial class CLOthingsContext : DbContext
{
    public CLOthingsContext(DbContextOptions<CLOthingsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CommunityPost> CommunityPosts { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<CustomerFavorite> CustomerFavorites { get; set; }

    public virtual DbSet<CustomerService> CustomerServices { get; set; }

    public virtual DbSet<GroupCart> GroupCarts { get; set; }

    public virtual DbSet<GroupCustomerFavorite> GroupCustomerFavorites { get; set; }

    public virtual DbSet<GroupCustomerService> GroupCustomerServices { get; set; }

    public virtual DbSet<GroupDiscountStandard> GroupDiscountStandards { get; set; }

    public virtual DbSet<GroupOrder> GroupOrders { get; set; }

    public virtual DbSet<GroupOrderDetail> GroupOrderDetails { get; set; }

    public virtual DbSet<GroupPaymentMethod> GroupPaymentMethods { get; set; }

    public virtual DbSet<GroupProduct> GroupProducts { get; set; }

    public virtual DbSet<GroupProductCategory> GroupProductCategories { get; set; }

    public virtual DbSet<GroupProductSpecification> GroupProductSpecifications { get; set; }

    public virtual DbSet<GroupSellerStatistic> GroupSellerStatistics { get; set; }

    public virtual DbSet<GroupShipper> GroupShippers { get; set; }

    public virtual DbSet<GroupSupplier> GroupSuppliers { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<PostComment> PostComments { get; set; }

    public virtual DbSet<PostImage> PostImages { get; set; }

    public virtual DbSet<PostLike> PostLikes { get; set; }

    public virtual DbSet<PostTaggedProduct> PostTaggedProducts { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductImg> ProductImgs { get; set; }

    public virtual DbSet<ProductSpecification> ProductSpecifications { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<SellerStatistic> SellerStatistics { get; set; }

    public virtual DbSet<Shipper> Shippers { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAddress> UserAddresses { get; set; }

    public virtual DbSet<UserFollow> UserFollows { get; set; }

    public virtual DbSet<UserOauth> UserOauths { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cart>(entity =>
        {
            entity.ToTable("Cart");

            entity.HasOne(d => d.ProductSpecification).WithMany(p => p.Carts)
                .HasForeignKey(d => d.ProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cart_Spec");

            entity.HasOne(d => d.User).WithMany(p => p.Carts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Cart_User");
        });

        modelBuilder.Entity<CommunityPost>(entity =>
        {
            entity.ToTable("CommunityPost");

            entity.Property(e => e.PostDate)
                .HasDefaultValueSql("(getdate())", "DF_CommunityPost_PostDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.CommunityPosts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_CommunityPost_User");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.ToTable("Coupon");

            entity.Property(e => e.CouponCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DiscountType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DiscountValue)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MinPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ValidEnd).HasColumnType("datetime");
            entity.Property(e => e.ValidStart).HasColumnType("datetime");
        });

        modelBuilder.Entity<CustomerFavorite>(entity =>
        {
            entity.ToTable("CustomerFavorite");

            entity.HasIndex(e => new { e.UserId, e.ProductId }, "UQ_Favorites").IsUnique();

            entity.HasOne(d => d.Product).WithMany(p => p.CustomerFavorites)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerFavorite_Product");

            entity.HasOne(d => d.User).WithMany(p => p.CustomerFavorites)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_CustomerFavorite_User");
        });

        modelBuilder.Entity<CustomerService>(entity =>
        {
            entity.ToTable("CustomerService");

            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Order).WithMany(p => p.CustomerServices)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_CustomerService_Order");
        });

        modelBuilder.Entity<GroupCart>(entity =>
        {
            entity.ToTable("GroupCart");

            entity.Property(e => e.AddDate)
                .HasDefaultValueSql("(getdate())", "DF_GroupCart_AddDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupCarts)
                .HasForeignKey(d => d.GroupProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupCart_Product");

            entity.HasOne(d => d.GroupProductSpecification).WithMany(p => p.GroupCarts)
                .HasForeignKey(d => d.GroupProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupCart_Spec");

            entity.HasOne(d => d.User).WithMany(p => p.GroupCarts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_UserId");
        });

        modelBuilder.Entity<GroupCustomerFavorite>(entity =>
        {
            entity.ToTable("GroupCustomerFavorite");

            entity.HasIndex(e => new { e.UserId, e.GroupProductId }, "UQ_GroupFavorites").IsUnique();

            entity.Property(e => e.AddDate)
                .HasDefaultValueSql("(getdate())", "DF_GroupCustomerFavorite_AddDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupCustomerFavorites)
                .HasForeignKey(d => d.GroupProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupCustomerFavorite_Product");

            entity.HasOne(d => d.User).WithMany(p => p.GroupCustomerFavorites)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_GroupCustomerFavorite_User");
        });

        modelBuilder.Entity<GroupCustomerService>(entity =>
        {
            entity.ToTable("GroupCustomerService");

            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.GroupOrder).WithMany(p => p.GroupCustomerServices)
                .HasForeignKey(d => d.GroupOrderId)
                .HasConstraintName("FK_GroupCustomerService_Order");
        });

        modelBuilder.Entity<GroupDiscountStandard>(entity =>
        {
            entity.ToTable("GroupDiscountStandard");

            entity.Property(e => e.DiscountRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.ThresholdAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ThresholdCount)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TierLevel)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupDiscountStandards)
                .HasForeignKey(d => d.GroupProductId)
                .HasConstraintName("FK_GroupDiscountStandard_Product");
        });

        modelBuilder.Entity<GroupOrder>(entity =>
        {
            entity.ToTable("GroupOrder");

            entity.Property(e => e.Freight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())", "DF_GroupOrder_OrderDate")
                .HasColumnType("datetime");
            entity.Property(e => e.PickupMethod)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ShipAddress)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ShipName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipPhone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ShipperDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.GroupShipper).WithMany(p => p.GroupOrders)
                .HasForeignKey(d => d.GroupShipperId)
                .HasConstraintName("FK_GroupOrder_Shipper");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.GroupOrders)
                .HasForeignKey(d => d.PaymentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrder_Payment");

            entity.HasOne(d => d.User).WithMany(p => p.GroupOrders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrder_User");
        });

        modelBuilder.Entity<GroupOrderDetail>(entity =>
        {
            entity.ToTable("GroupOrderDetail");

            entity.Property(e => e.Discount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.GroupOrder).WithMany(p => p.GroupOrderDetails)
                .HasForeignKey(d => d.GroupOrderId)
                .HasConstraintName("FK_GroupOrderDetail_Order");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupOrderDetails)
                .HasForeignKey(d => d.GroupProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrderDetail_Product");

            entity.HasOne(d => d.GroupProductSpecification).WithMany(p => p.GroupOrderDetails)
                .HasForeignKey(d => d.GroupProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrderDetail_Spec");
        });

        modelBuilder.Entity<GroupPaymentMethod>(entity =>
        {
            entity.ToTable("GroupPaymentMethod");

            entity.Property(e => e.CardBrand)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ExpireAt)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.GroupPaymentMethods)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_GroupPaymentMethod_User");
        });

        modelBuilder.Entity<GroupProduct>(entity =>
        {
            entity.ToTable("GroupProduct");

            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductImg).HasMaxLength(255);
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SalesEnd).HasColumnType("datetime");
            entity.Property(e => e.SalesStart).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.GroupProductCategory).WithMany(p => p.GroupProducts)
                .HasForeignKey(d => d.GroupProductCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupProduct_Category");

            entity.HasOne(d => d.GroupSupplier).WithMany(p => p.GroupProducts)
                .HasForeignKey(d => d.GroupSupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupProduct_Supplier");
        });

        modelBuilder.Entity<GroupProductCategory>(entity =>
        {
            entity.ToTable("GroupProductCategory");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(255);
        });

        modelBuilder.Entity<GroupProductSpecification>(entity =>
        {
            entity.ToTable("GroupProductSpecification");

            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Size)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupProductSpecifications)
                .HasForeignKey(d => d.GroupProductId)
                .HasConstraintName("FK_GroupProductSpecification_Product");
        });

        modelBuilder.Entity<GroupSellerStatistic>(entity =>
        {
            entity.HasKey(e => e.GroupSellerStatisticsId);

            entity.ToTable("GroupSellerStatistic");

            entity.Property(e => e.AddCartCount).HasDefaultValue(0, "DF_GroupSellerStatistic_AddCartCount");
            entity.Property(e => e.CheckoutCount).HasDefaultValue(0, "DF_GroupSellerStatistic_CheckoutCount");
            entity.Property(e => e.FavorCount).HasDefaultValue(0, "DF_GroupSellerStatistic_FavorCount");
            entity.Property(e => e.StatisticDate)
                .HasDefaultValueSql("(getdate())", "DF_GroupSellerStatistic_StatisticDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ViewCount).HasDefaultValue(0, "DF_GroupSellerStatistic_ViewCount");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupSellerStatistics)
                .HasForeignKey(d => d.GroupProductId)
                .HasConstraintName("FK_GroupSellerStatistic_Product");

            entity.HasOne(d => d.GroupSupplier).WithMany(p => p.GroupSellerStatistics)
                .HasForeignKey(d => d.GroupSupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupSellerStatistic_Supplier");
        });

        modelBuilder.Entity<GroupShipper>(entity =>
        {
            entity.ToTable("GroupShipper");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipperName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<GroupSupplier>(entity =>
        {
            entity.ToTable("GroupSupplier");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.ContactName).HasMaxLength(100);
            entity.Property(e => e.ContactTitle).HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.ToTable("Invoice");

            entity.Property(e => e.CarrierCode).HasMaxLength(50);
            entity.Property(e => e.CompanyName).HasMaxLength(100);
            entity.Property(e => e.DonationCode).HasMaxLength(50);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.InvoiceDate)
                .HasDefaultValueSql("(getdate())", "DF_Invoice_InvoiceDate")
                .HasColumnType("datetime");
            entity.Property(e => e.InvoiceType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RandomCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TaxCode).HasMaxLength(50);
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Order).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_Invoice_Order");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("Order");

            entity.Property(e => e.Freight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())", "DF_Order_OrderDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ShipAddress)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ShipName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipPhone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ShippedDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Coupon).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("FK_Order_Coupon");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.Orders)
                .HasForeignKey(d => d.PaymentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Payment");

            entity.HasOne(d => d.Shipper).WithMany(p => p.Orders)
                .HasForeignKey(d => d.ShipperId)
                .HasConstraintName("FK_Order_Shipper");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_User");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.ToTable("OrderDetail");

            entity.Property(e => e.Discount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Coupon).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("FK_OrderDetail_Coupon");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_OrderDetail_Order");

            entity.HasOne(d => d.ProductSpecification).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetail_Spec");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.ToTable("PaymentMethod");

            entity.Property(e => e.CardBrand)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ExpireAt)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.PaymentMethods)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PaymentMethod_User");
        });

        modelBuilder.Entity<PostComment>(entity =>
        {
            entity.ToTable("PostComment");

            entity.Property(e => e.CommentDate)
                .HasDefaultValueSql("(getdate())", "DF_PostComment_CommentDate")
                .HasColumnType("datetime");
            entity.Property(e => e.CommentText).IsRequired();

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostComments)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostComment_Post");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .HasConstraintName("FK_PostComment_Parent");

            entity.HasOne(d => d.User).WithMany(p => p.PostComments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostComment_User");
        });

        modelBuilder.Entity<PostImage>(entity =>
        {
            entity.ToTable("PostImage");

            entity.Property(e => e.ImageFileName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.SortOrder).HasDefaultValue(1, "DF_PostImage_SortOrder");

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostImages)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostImage_Post");
        });

        modelBuilder.Entity<PostLike>(entity =>
        {
            entity.HasKey(e => e.PostLikesId);

            entity.ToTable("PostLike");

            entity.HasIndex(e => new { e.CommunityPostId, e.UserId }, "UQ_PostLikes").IsUnique();

            entity.Property(e => e.LikeDate)
                .HasDefaultValueSql("(getdate())", "DF_PostLike_LikeDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostLikes)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostLike_Post");

            entity.HasOne(d => d.User).WithMany(p => p.PostLikes)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostLike_User");
        });

        modelBuilder.Entity<PostTaggedProduct>(entity =>
        {
            entity.ToTable("PostTaggedProduct");

            entity.Property(e => e.ProductRoute)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostTaggedProducts)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostTaggedProduct_Post");

            entity.HasOne(d => d.Product).WithMany(p => p.PostTaggedProducts)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostTaggedProduct_Product");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");

            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SalesEndDate).HasColumnType("datetime");
            entity.Property(e => e.SalesStartDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.ProductCategory).WithMany(p => p.Products)
                .HasForeignKey(d => d.ProductCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_Category");

            entity.HasOne(d => d.Supplier).WithMany(p => p.Products)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_Supplier");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.ToTable("ProductCategory");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Description).HasMaxLength(255);
        });

        modelBuilder.Entity<ProductImg>(entity =>
        {
            entity.ToTable("ProductImg");

            entity.Property(e => e.ProductImgFile)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImg)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductImg_Product");
        });

        modelBuilder.Entity<ProductSpecification>(entity =>
        {
            entity.ToTable("ProductSpecification");

            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Size)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSpecifications)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductSpecification_Product");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.ToTable("Review");

            entity.Property(e => e.ReviewDatetime)
                .HasDefaultValueSql("(getdate())", "DF_Review_ReviewDatetime")
                .HasColumnType("datetime");
            entity.Property(e => e.ReviewImage).HasMaxLength(255);

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.OrderDetailId)
                .HasConstraintName("FK_Review_OrderDetail");

            entity.HasOne(d => d.User).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_User");
        });

        modelBuilder.Entity<SellerStatistic>(entity =>
        {
            entity.HasKey(e => e.SellerStatisticsId);

            entity.ToTable("SellerStatistic");

            entity.Property(e => e.AddCartCount).HasDefaultValue(0, "DF_SellerStatistic_AddCartCount");
            entity.Property(e => e.CheckoutCount).HasDefaultValue(0, "DF_SellerStatistic_CheckoutCount");
            entity.Property(e => e.FavorCount).HasDefaultValue(0, "DF_SellerStatistic_FavorCount");
            entity.Property(e => e.StatisticsDate)
                .HasDefaultValueSql("(getdate())", "DF_SellerStatistic_StatisticsDate")
                .HasColumnType("datetime");
            entity.Property(e => e.ViewCount).HasDefaultValue(0, "DF_SellerStatistic_ViewCount");

            entity.HasOne(d => d.Product).WithMany(p => p.SellerStatistics)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_SellerStatistic_Product");
        });

        modelBuilder.Entity<Shipper>(entity =>
        {
            entity.ToTable("Shipper");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipperName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.ToTable("Supplier");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.ContactEmail).HasMaxLength(100);
            entity.Property(e => e.ContactName).HasMaxLength(100);
            entity.Property(e => e.ContactTitle).HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CountryCode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())", "DF_User_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TwoFactorEnabled).HasDefaultValue(false, "DF_User_TwoFactorEnabled");
            entity.Property(e => e.TwoFactorSecret)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())", "DF_User_UpdatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserAddress>(entity =>
        {
            entity.ToTable("UserAddress");

            entity.Property(e => e.AddressDetail).HasMaxLength(255);
            entity.Property(e => e.IsDefault).HasDefaultValue(false, "DF_UserAddress_IsDefault");
            entity.Property(e => e.PostalCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RecipientName).HasMaxLength(100);
            entity.Property(e => e.RecipientPhone).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.UserAddresses)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserAddress_User");
        });

        modelBuilder.Entity<UserFollow>(entity =>
        {
            entity.ToTable("UserFollow");

            entity.HasIndex(e => new { e.FollowerId, e.FollowingId }, "UQ_UserFollows").IsUnique();

            entity.Property(e => e.FollowDate)
                .HasDefaultValueSql("(getdate())", "DF_UserFollow_FollowDate")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Follower).WithMany(p => p.UserFollowFollowers)
                .HasForeignKey(d => d.FollowerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollow_Follower");

            entity.HasOne(d => d.Following).WithMany(p => p.UserFollowFollowings)
                .HasForeignKey(d => d.FollowingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollow_Following");
        });

        modelBuilder.Entity<UserOauth>(entity =>
        {
            entity.ToTable("UserOAuth");

            entity.Property(e => e.UserOauthId).HasColumnName("UserOAuthId");
            entity.Property(e => e.AccessToken)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ExpiresAt).HasColumnType("datetime");
            entity.Property(e => e.Provider)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ProviderUserId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.RefreshToken)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())", "DF_UserOAuth_UpdatedAt")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserOauths)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserOAuth_User");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.ToTable("UserProfile");

            entity.Property(e => e.Avatar)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.LastName).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.UserProfiles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserProfile_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}