// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CLOthings.Models;

public partial class CommunityPost
{
    public int CommunityPostId { get; set; }

    public int UserId { get; set; }

    [Required(ErrorMessage = "貼文內容不能為空白！")]
    [Display(Name = "貼文內容")]
    public string Content { get; set; }

    public DateTime PostDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<PostImage> PostImages { get; set; } = new List<PostImage>();

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual ICollection<PostTaggedProduct> PostTaggedProducts { get; set; } = new List<PostTaggedProduct>();

    public virtual User User { get; set; }
}