// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string CouponCode { get; set; }

    public string DiscountType { get; set; }

    public string DiscountValue { get; set; }

    public decimal MinPrice { get; set; }

    public DateTime? ValidStart { get; set; }

    public DateTime? ValidEnd { get; set; }

    public int? UsageLimit { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}