// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupProductSpecification
{
    public int SpecificationId { get; set; }

    public int ProductId { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public virtual ICollection<GroupCart> GroupCarts { get; set; } = new List<GroupCart>();

    public virtual GroupProduct Product { get; set; }
}