// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupCustomerFavorite
{
    public int GroupCustomerFavoriteId { get; set; }

    public int UserId { get; set; }

    public int GroupProductId { get; set; }

    public DateTime AddDate { get; set; }

    public virtual GroupProduct GroupProduct { get; set; }

    public virtual User User { get; set; }
}