// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupOrderDetail
{
    public int OrderDetailId { get; set; }

    public int ProductId { get; set; }

    public string SpecificationId { get; set; }

    public int OrderId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public decimal? Discount { get; set; }

    public virtual GroupOrder Order { get; set; }

    public virtual GroupProduct Product { get; set; }
}