// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupOrder
{
    public int OrderId { get; set; }

    public string CustomerId { get; set; }

    public string EmployeeId { get; set; }

    public string Status { get; set; }

    public decimal TotalPrice { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime? ShipperDate { get; set; }

    public int? ShipperId { get; set; }

    public string PickupMethod { get; set; }

    public string ShipName { get; set; }

    public string ShipAddress { get; set; }

    public string ShipPhone { get; set; }

    public decimal Freight { get; set; }

    public int PaymentMethodId { get; set; }

    public virtual ICollection<GroupCustomerService> GroupCustomerServices { get; set; } = new List<GroupCustomerService>();

    public virtual ICollection<GroupOrderDetail> GroupOrderDetails { get; set; } = new List<GroupOrderDetail>();

    public virtual GroupPaymentMethod PaymentMethod { get; set; }

    public virtual GroupShipper Shipper { get; set; }
}