// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupProduct
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int SupplierId { get; set; }

    public int CategoryId { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public DateTime? SalesStart { get; set; }

    public DateTime? SalesEnd { get; set; }

    public string ProductImg { get; set; }

    public virtual GroupProductsCategory Category { get; set; }

    public virtual ICollection<GroupCart> GroupCarts { get; set; } = new List<GroupCart>();

    public virtual ICollection<GroupDiscountStandard> GroupDiscountStandards { get; set; } = new List<GroupDiscountStandard>();

    public virtual ICollection<GroupOrderDetail> GroupOrderDetails { get; set; } = new List<GroupOrderDetail>();

    public virtual ICollection<GroupProductSpecification> GroupProductSpecifications { get; set; } = new List<GroupProductSpecification>();

    public virtual ICollection<GroupSellerStatistic> GroupSellerStatistics { get; set; } = new List<GroupSellerStatistic>();

    public virtual GroupSupplier Supplier { get; set; }
}