// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupCart
{
    public int CartItemId { get; set; }

    public string CartId { get; set; }

    public int ProductId { get; set; }

    public int SpecificationId { get; set; }

    public int Quantity { get; set; }

    public DateTime AddDate { get; set; }

    public virtual GroupProduct Product { get; set; }

    public virtual GroupProductSpecification Specification { get; set; }
}