// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupCustomerService
{
    public int CustomerServiceId { get; set; }

    public int OrderId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Content { get; set; }

    public string Title { get; set; }

    public virtual GroupOrder Order { get; set; }
}