// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupDiscountStandard
{
    public int TierId { get; set; }

    public int ProductId { get; set; }

    public string TierLevel { get; set; }

    public string ThresholdCount { get; set; }

    public decimal? ThresholdAmount { get; set; }

    public decimal? DiscountRate { get; set; }

    public virtual GroupProduct Product { get; set; }
}