// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupSellerStatistic
{
    public int StatisticsId { get; set; }

    public int SupplierId { get; set; }

    public int ProductId { get; set; }

    public int? AddCartCount { get; set; }

    public int? CheckoutCount { get; set; }

    public int? ViewCount { get; set; }

    public int? FavorCount { get; set; }

    public DateTime StatisticDate { get; set; }

    public virtual GroupProduct Product { get; set; }

    public virtual GroupSupplier Supplier { get; set; }
}