// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupPaymentMethod
{
    public int PaymentMethodId { get; set; }

    public string UserId { get; set; }

    public string Provider { get; set; }

    public string Token { get; set; }

    public string CardBrand { get; set; }

    public string ExpireAt { get; set; }

    public bool IsDefault { get; set; }

    public virtual ICollection<GroupOrder> GroupOrders { get; set; } = new List<GroupOrder>();
}