// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupProductSpecification
{
    public int GroupProductSpecificationId { get; set; }

    public int GroupProductId { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public virtual ICollection<GroupCart> GroupCarts { get; set; } = new List<GroupCart>();

    public virtual ICollection<GroupOrderDetail> GroupOrderDetails { get; set; } = new List<GroupOrderDetail>();

    public virtual GroupProduct GroupProduct { get; set; }
}