// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class GroupCustomerFavorite
{
    public int FavoriteId { get; set; }

    public string UserId { get; set; }

    public string ProductId { get; set; }

    public DateTime AddDate { get; set; }
}