// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class PostImage
{
    public int ImageId { get; set; }

    public int PostId { get; set; }

    public string ImageFileName { get; set; }

    public int SortOrder { get; set; }

    public virtual CommunityPost Post { get; set; }
}