// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class PostLike
{
    public int PostLikesId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public DateTime LikeDate { get; set; }

    public virtual CommunityPost Post { get; set; }

    public virtual User User { get; set; }
}