// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class PostComment
{
    public int CommentId { get; set; }

    public int? ParentCommentId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public string CommentText { get; set; }

    public DateTime CommentDate { get; set; }

    public virtual ICollection<PostComment> InverseParentComment { get; set; } = new List<PostComment>();

    public virtual PostComment ParentComment { get; set; }

    public virtual CommunityPost Post { get; set; }

    public virtual User User { get; set; }
}