// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int SupplierId { get; set; }

    public int CategoryId { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public DateTime? SalesStartDate { get; set; }

    public DateTime? SalesEndDate { get; set; }

    public virtual ProductsCategory Category { get; set; }

    public virtual ICollection<CustomerFavorite> CustomerFavorites { get; set; } = new List<CustomerFavorite>();

    public virtual ICollection<ProductImg> ProductImgs { get; set; } = new List<ProductImg>();

    public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; } = new List<ProductSpecification>();

    public virtual ICollection<SellerStatistic> SellerStatistics { get; set; } = new List<SellerStatistic>();

    public virtual Supplier Supplier { get; set; }
}