// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int UserId { get; set; }

    public int Rating { get; set; }

    public string ReviewComment { get; set; }

    public DateTime ReviewDatetime { get; set; }

    public string ReviewImage { get; set; }

    public int OrderDetailId { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual User User { get; set; }
}