// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int UserType { get; set; }

    public int Status { get; set; }

    public bool? TwoFactorEnabled { get; set; }

    public string TwoFactorSecret { get; set; }

    public string CountryCode { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<CommunityPost> CommunityPosts { get; set; } = new List<CommunityPost>();

    public virtual ICollection<CustomerFavorite> CustomerFavorites { get; set; } = new List<CustomerFavorite>();

    public virtual ICollection<GroupCart> GroupCarts { get; set; } = new List<GroupCart>();

    public virtual ICollection<GroupCustomerFavorite> GroupCustomerFavorites { get; set; } = new List<GroupCustomerFavorite>();

    public virtual ICollection<GroupOrder> GroupOrders { get; set; } = new List<GroupOrder>();

    public virtual ICollection<GroupPaymentMethod> GroupPaymentMethods { get; set; } = new List<GroupPaymentMethod>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PaymentMethod> PaymentMethods { get; set; } = new List<PaymentMethod>();

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<UserAddress> UserAddresses { get; set; } = new List<UserAddress>();

    public virtual ICollection<UserFollow> UserFollowFollowers { get; set; } = new List<UserFollow>();

    public virtual ICollection<UserFollow> UserFollowFollowings { get; set; } = new List<UserFollow>();

    public virtual ICollection<UserOauth> UserOauths { get; set; } = new List<UserOauth>();

    public virtual ICollection<UserProfile> UserProfiles { get; set; } = new List<UserProfile>();
}