// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CLOthings.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CLOthings.Models;

public partial class User
{

    
    public int UserId { get; set; }

    [Display(Name = "使用者名稱")]
    public string Username { get; set; }

    [Display(Name = "帳號")]
    public string Account { get; set; }

    [Display(Name = "密碼")]
    public string Password { get; set; }

    [Display(Name = "電子郵件")]
    public string Email { get; set; }

    [Display(Name = "電話")]
    public string Phone { get; set; }


    [Display(Name = "建立時間")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd  HH:mm:ss}", ApplyFormatInEditMode = true)]
    public DateTime CreatedAt { get; set; }

    [Display(Name = "更新時間")]
    [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd  HH:mm:ss}", ApplyFormatInEditMode = true)]
    public DateTime UpdatedAt { get; set; }


    [Display(Name = "使用者類型")]
    public UserTypeEnum UserType { get; set; }


    [Display(Name = "帳號狀態")]
    public StatusEnum Status { get; set; } = StatusEnum.Active;

    [Display(Name = "認證狀態")]
    public bool? TwoFactorEnabled { get; set; }
    [Display(Name = "認證金鑰")]
    public string TwoFactorSecret { get; set; }
    [Display(Name = "區碼")]
    public string CountryCode { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<CommunityPost> CommunityPosts { get; set; } = new List<CommunityPost>();

    public virtual ICollection<CustomerFavorite> CustomerFavorites { get; set; } = new List<CustomerFavorite>();

    public virtual ICollection<GroupCart> GroupCarts { get; set; } = new List<GroupCart>();

    public virtual ICollection<GroupCustomerFavorite> GroupCustomerFavorites { get; set; } = new List<GroupCustomerFavorite>();

    public virtual ICollection<GroupOrder> GroupOrders { get; set; } = new List<GroupOrder>();

    public virtual ICollection<GroupPaymentMethod> GroupPaymentMethods { get; set; } = new List<GroupPaymentMethod>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PaymentMethod> PaymentMethods { get; set; } = new List<PaymentMethod>();

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<UserAddress> UserAddresses { get; set; } = new List<UserAddress>();

    public virtual ICollection<UserFollow> UserFollowFollowers { get; set; } = new List<UserFollow>();

    public virtual ICollection<UserFollow> UserFollowFollowings { get; set; } = new List<UserFollow>();

    public virtual ICollection<UserOauth> UserOauths { get; set; } = new List<UserOauth>();

    public virtual ICollection<UserProfile> UserProfiles { get; set; } = new List<UserProfile>();
}